version: '3.5'

services:
  mkdocs:
    build: .
    restart: always
    ports:
      - 8000:8000
    environment:
      - SSH_AUTH_SOCK=$SSH_AUTH_SOCK
    volumes:
      - $PWD:/docs
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK